#longitude offset to vehicle center(center of rear axle)
long_offset_mid: 6.0 #unit: m

#lateral offset to vehicle center(center of rear axle)
lat_offset_mid: 0.0 #unit: m

#angle offset to vehicle center(center of rear axle)
angular_deviation_mid: 90.0 #degree

#longitude offset to vehicle center(center of rear axle)
long_offset_left: 6.0 #unit: m

#lateral offset to vehicle center(center of rear axle)
lat_offset_left: -1.12 #unit: m

#longtitude offset to vehicle center(center of rear axle)
angular_deviation_left: 165.0 #degree

#longitude offset to vehicle center(center of rear axle)
long_offset_right: 6.0 #unit: m

#lateral offset to vehicle center(center of rear axle)
lat_offset_right: 1.12 #unit: m

#longtitude offset to vehicle center(center of rear axle)
angular_deviation_right: 15.0 #degree